name: aprendizado_de_maquina
channels:
  - defaults
dependencies:
  - scikit-learn
  - jupyter
  - requests
  - matplotlib
  - numpy
  - pandas
  - pillow
  - python=3.11
  - pip
  - scipy
  - pip:
      - annotated-types==0.7.0
      - cachetools==5.5.2
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.0rc1
      - google-api-python-client==2.169.0
      - google-auth==2.40.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - httplib2==0.22.0
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - python-dotenv==1.1.0
      - rsa==4.9.1
      - seaborn==0.13.2
      - tqdm==4.67.1
      - typing-inspection==0.4.0
      - uritemplate==4.1.1
