name: aprendizado_de_maquina
channels:
  - defaults
dependencies:
  - scikit-learn
  - jupyter
  - requests
  - matplotlib
  - numpy
  - pandas
  - pillow
  - python=3.11
  - pip
  - scipy
  - pip:
      - absl-py==2.3.0
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - cachetools==5.5.2
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.0rc1
      - google-api-python-client==2.169.0
      - google-auth==2.40.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - google-pasta==0.2.0
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.0
      - grpcio-status==1.71.0
      - h5py==3.14.0
      - httplib2==0.22.0
      - keras==3.10.0
      - libclang==18.1.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - namex==0.1.0
      - opt-einsum==3.4.0
      - optree==0.16.0
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - python-dotenv==1.1.0
      - rich==14.0.0
      - rsa==4.9.1
      - seaborn==0.13.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - tqdm==4.67.1
      - typing-inspection==0.4.0
      - uritemplate==4.1.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
